// Generated by https://quicktype.io

export interface IGetMyEventsResponse {
  id: string;
  title: string;
  description: string;
  status: string;
  isPrivate: string;
  createdAt: string;
  place: string;
  communityId: string;
  link: null;
  score: number;
  dateTime: string;
  eventCategoryId: string;
}
