// Generated by https://quicktype.io

export interface GetEventByIDResponse {
    id:          string;
    title:       string;
    description: string;
    status:      string;
    isPrivate:   string;
    createdAt:   string;
    place:       string;
    communityId: string;
    dateTime:    string;
    community:   Community;
    Consumable:  any[];
}

export interface Community {
    id:          string;
    name:        string;
    description: string;
    color:       string;
    createdAt:   string;
}
