// Generated by https://quicktype.io

export interface Authentication {
  access_token: string | null;
  isAuth: boolean;
  user: User | null;
  error: string | null;
}

export interface User {
  id: string;
  email: string;
  name: string;
  role: string;
  isActive: boolean;
  lastname: string;
}
